# -----------------------------------------------------------------------------
# Site settings - Chinese Version
# 网站设置 - 中文版本
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead
first_name: 俊
middle_name: 
last_name: 周
contact_note: 
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  中国地质大学博士研究生，阿尔伯塔大学访问博士生。研究方向包括3D计算机视觉、手-物交互和物理感知生成建模。
footer_text: >
  由 <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> 和 <a href="https://github.com/alshedivat/al-folio">al-folio</a> 主题驱动。
keywords: jekyll, jekyll-theme, academic-website, portfolio-website # add your own keywords or leave empty
lang: zh # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://zhoujun-7.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false
socials_in_search: false
posts_in_search: false
bib_search: false

# Dimensions
max_width: 930px

# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# see https://schema.org/docs/faq.html for more information
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

# For Google Analytics, see https://support.google.com/analytics/answer/10447272?hl=en&ref_topic=14088998&sjid=5129943941510317771-SA#zippy=%2Cgoogle-sites
# and follow the instructions for Google Sites. You will need to create a Google Analytics property and copy the Google tag ID.
google_analytics: # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
cronitor_analytics: # cronitor RUM analytics site ID (format: XXXXXXXXX)
pirsch_analytics: # your Pirsch analytics site ID (length 32 characters)
openpanel_analytics: # your Openpanel analytics client ID (format: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)

# For Google Search Console, see https://support.google.com/webmasters/answer/9008080?hl=en#meta_tag_verification&zippy=%2Chtml-tag
google_site_verification: # your google-site-verification ID (Google Search Console)
bing_site_verification: # out your bing-site-verification ID (Bing Webmaster)

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: 博客 # blog_name will be displayed in your blog page
blog_description: 一个简单的学术博客主题
permalink: /blog/:year/:title/
lsi: false # produce an index for related posts

# Pagination
pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# Giscus comments (RECOMMENDED)
# Follow instructions on https://giscus.app/ to setup for your repo to fill out the information below.
giscus:
  repo: # <your-github-user-name>/<your-github-repo-name>
  repo_id: # leave empty or specify your repo_id (see https://giscus.app/)
  category: 评论 # name of the category under which discussions will be created
  category_id: # leave empty or specify your category_id (see https://giscus.app/)
  mapping: title # identify discussions by post title
  strict: 1 # use strict identification mode
  reactions_enabled: 1 # enable (1) or disable (0) emoji reactions
  input_position: bottom # whether to display input form below (bottom) or above (top) the comments
  dark_theme: dark # name of the dark color scheme (preferred works well with al-folio dark mode)
  light_theme: light # name of the light color scheme (preferred works well with al-folio dark mode)
  emit_metadata: 0
  lang: zh

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  _posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  _pages:
    output: true
    permalink: /:title/
  _books:
    output: true
    permalink: /:collection/:title/
  _bibliography:
    output: true
    permalink: /:collection/:title/

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

plugins:
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  compress_javascript: false # set to false since we are using terser as the js minifier
  exclude: ["robots.txt", "assets/js/search/*.js"]

# -----------------------------------------------------------------------------
# Terser
# -----------------------------------------------------------------------------

terser:
  compress:
    drop_console: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  posts:
    enabled: [year, tags, categories] # enables year, tag and category archives (remove if you need to disable one of them).
    permalinks:
      year: "/blog/:year/"
      tags: "/blog/:type/:name/"
      categories: "/blog/:type/:name/"
  books:
    enabled: [year, tags, categories] # enables year, tag and category archives (remove if you need to disable one of them).

display_tags: ["formatting", "images", "links", "math", "code", "blockquotes"] # these tags will be displayed on the front page of your blog
display_categories: ["external-services"] # these categories will be displayed on the front page of your blog

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Zhou]
  first_name: [Jun]

  style: apa
  locale: zh

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: 详情

  query: "@*"
  group_by: year
  group_order: descending

# Display different badges withs stats for your publications
# Customize badge behavior in _layouts/bib.liquid
enable_publication_badges:
  altmetric: true # Altmetric badge (Customization options: https://badge-docs.altmetric.com/index.html)
  dimensions: true # Dimensions badge (Customization options: https://badge.dimensions.ai/)
  google_scholar: true # Google Scholar badge (https://scholar.google.com/intl/en/scholar/citations.html)
  inspirehep: true # Inspire HEP badge (https://help.inspirehep.net/knowledge-base/citation-metrics/)

# Filter out certain bibtex entry keywords used internally from the bib output
filtered_bibtex_keywords:
  [
    abbr,
    abstract,
    arxiv,
    bibtex_show,
    html,
    pdf,
    supp,
    video,
    code,
    poster,
    slides,
    selected,
    featured,
    note,
    preview,
    doi,
    url,
    eprint,
    isbn,
    issn,
    month,
    note,
    number,
    pages,
    publisher,
    school,
    series,
    volume,
    keywords,
    hide,
    abbr,
    abstract,
    arxiv,
    bibtex_show,
    html,
    pdf,
    supp,
    video,
    code,
    poster,
    slides,
    selected,
    featured,
    note,
    preview,
    doi,
    url,
    eprint,
    isbn,
    issn,
    month,
    note,
    number,
    pages,
    publisher,
    school,
    series,
    volume,
    keywords,
    hide,
  ]

# -----------------------------------------------------------------------------
# Social Media
# -----------------------------------------------------------------------------

# Social media links
social:
  - title: email
    url: mailto:jun.zhou@ualberta.ca
  - title: github
    url: https://github.com/zhoujun-7
  - title: linkedin
    url: https://www.linkedin.com/in/zhoujun-7
  - title: google-scholar
    url: https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID

# Enable social media icons in navbar
enable_navbar_social: false # enables displaying social links in the navbar on the about page

# -----------------------------------------------------------------------------
# CV
# -----------------------------------------------------------------------------

# CV settings
cv:
  # Enable CV download button
  download_pdf: true
  # CV PDF file path (relative to assets/pdf/)
  pdf_filename: cv.pdf
  # CV PDF file description
  pdf_description: "下载简历 (PDF)"

# -----------------------------------------------------------------------------
# Projects
# -----------------------------------------------------------------------------

# Project settings
projects:
  # Enable project filtering by category
  filter_by_category: true
  # Enable project search
  search: true
  # Enable project pagination
  pagination: true
  # Number of projects per page
  per_page: 12

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

# Blog settings
blog:
  # Enable blog search
  search: true
  # Enable blog pagination
  pagination: true
  # Number of posts per page
  per_page: 10
  # Enable related posts
  related_posts: true
  # Number of related posts to show
  max_related: 5

# -----------------------------------------------------------------------------
# Search
# -----------------------------------------------------------------------------

# Search settings
search:
  # Enable search functionality
  enabled: true
  # Search placeholder text
  placeholder: "搜索..."
  # Search button text
  button_text: "搜索"
  # Search results text
  results_text: "搜索结果"
  # No results text
  no_results_text: "没有找到结果"

# -----------------------------------------------------------------------------
# Comments
# -----------------------------------------------------------------------------

# Comments settings
comments:
  # Enable comments
  enabled: true
  # Comments provider (disqus, giscus, etc.)
  provider: giscus
  # Comments title
  title: "评论"
  # Comments placeholder
  placeholder: "写下你的评论..."
  # Submit button text
  submit_text: "提交评论"

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

# Newsletter settings
newsletter:
  # Enable newsletter
  enabled: false
  # Newsletter title
  title: "订阅更新"
  # Newsletter description
  description: "订阅我们的新闻通讯，获取最新更新。"
  # Newsletter placeholder
  placeholder: "输入你的邮箱地址"
  # Newsletter button text
  button_text: "订阅"
  # Newsletter success message
  success_message: "订阅成功！"
  # Newsletter error message
  error_message: "订阅失败，请重试。"

# -----------------------------------------------------------------------------
# Footer
# -----------------------------------------------------------------------------

# Footer settings
footer:
  # Enable footer
  enabled: true
  # Footer text
  text: "© 2024 周俊. 保留所有权利."
  # Footer links
  links:
    - title: "关于"
      url: "/about_zh/"
    - title: "博客"
      url: "/blog/"
    - title: "论文"
      url: "/publications/"
    - title: "项目"
      url: "/projects/"
    - title: "简历"
      url: "/cv/"
    - title: "教学"
      url: "/teaching/"
    - title: "团队"
      url: "/profiles/"

# -----------------------------------------------------------------------------
# Language
# -----------------------------------------------------------------------------

# Language settings
language:
  # Default language
  default: zh
  # Available languages
  available:
    - en
    - zh
  # Language names
  names:
    en: "English"
    zh: "中文"
  # Language URLs
  urls:
    en: "/about/"
    zh: "/about_zh/"
